### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by ekirk81** [NordicGamerFE/Ocean-Outlast#170]
Version: [Easy/Expert] [Version number]

Launcher: [ATL, Curseforge or Others like MultiMC]

Description:
No sound on modpack start.

Under settings 'Output system:default' any attempt to change this results in being kicked back to main menu. That audio drivers weren't recognized.

Expected Result:
[Describe the result you expected]

Actual Result:
[Describe the actual result]

Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Form is not filled in with all details.

**Comment by Phatboysquad** [comment]
We should open this back up, I can literally fill out the rest of the form for this not very smart person that closed this as "completed" because they couldn't spend one second to read the actual issue. Which I myself am experiencing and would have liked to see some sort of feedback instead of "Form is not filled in with all details." Here is a comment to which I will properly feed into your forum to hopefully get some actual help from. 

Version: [Easy/Expert] [Version number]:
_Normal mode? I'm not sure if you're asking for the difficulty im playing on or not, but the problem exists on the menu as well, not just while playing the game_ / _As for the Version I'm playing its @V70_

Launcher: [ATL, Curseforge or Others like MultiMC]:
_I'm using Curseforge_

Description: [Describe your issue]: 
_No sound at all, from the moment the game was booted up, to loading into a world. Tried to tweak with the settings in the menu and was experiencing the same issue:
Clicking on the audio settings and trying to select 'Output: System Default' would give you a big red screen reading: "Failed to read sound devices Your audio driver might not support this feature"._

Expected Result:
[Describe the result you expected]:
_I expected to load into the game and hear some audio. I expected to be able to click on the audio settings and change them if I wanted too. _

Actual Result:
[Describe the actual result]:
_My result was not being able to hear anything at all, and clicking on the audio output didn't help change my settings at all._

Did you add additional mods?
[yes/no]: _No. Just downloaded the game straight from Curseforge and hit play._
[if yes, what mods and what versions?]: N/A

[If applicable, post any reports or logs related to the bug here] : N/A

**Comment by Phatboysquad** [comment]
![image](https://github.com/user-attachments/assets/0fd4bb48-2321-41a6-8ab2-74bc6f870595)

**Comment by NordicGamerFE** [comment]
Since you tought it so nessecery to insult me and you are clearly so much smarter then me i figured you can find the issue yourself. hint its very easy to fix.

**Comment by Phatboysquad** [comment]
Yeah @NordicGamerFE  You shouldnt be on a forum for HELPING PEOPLE BUD. Your literally going against being a guide cause your a sad salty human being that cant help anyone. So instead of playing the game of being of freaking mod of a forum for a Minecraft game for a second. Why dont you play the game of doing your damn job? AND HELP PEOPLE ON THE FORUM!

**Comment by NordicGamerFE** [comment]
For anyone coming in here wondering what the issue is its simple play the latest version.
