### ISSUE TITLE
Sound Issues (No sound at all)

### ISSUE THREAD

**Issue by Phatboysquad** [NordicGamerFE/Ocean-Outlast#176]
Version: [Easy/Expert] [Version number]:
_Normal mode? I'm not sure if you're asking for the difficulty im playing on or not, but the problem exists on the menu as well, not just while playing the game / As for the Version I'm playing its at v70_

Launcher: [ATL, Curseforge or Others like MultiMC]:
_I'm using Curseforge_

Description: [Describe your issue]:
_No sound at all, from the moment the game was booted up, to loading into a world. Tried to tweak with the settings in the menu and was experiencing the same issue:
Clicking on the audio settings and trying to select 'Output: System Default' would give you a big red screen reading: "Failed to read sound devices Your audio driver might not support this feature"._

Expected Result:
[Describe the result you expected]:
_I expected to load into the game and hear some audio. I expected to be able to click on the audio settings and change them if I wanted too. _

Actual Result:
[Describe the actual result]:
_My result was not being able to hear anything at all, and clicking on the audio output didn't help change my settings at all._

Did you add additional mods?
[yes/no]: _No. Just downloaded the game straight from Curseforge and hit play._
[if yes, what mods and what versions?]: N/A

[If applicable, post any reports or logs related to the bug here] : N/A

![image](https://github.com/user-attachments/assets/07749f6d-5dae-4ced-b8ee-d2688ef7712f)

**Comment by Phatboysquad** [comment]
I hope this form is filled out enough for you Mr. @NordicGamerFE

**Comment by Phatboysquad** [comment]
@NordicGamerFE so do you guys just hate newcomers that don't really understand how to use your dumb forums? Im really trying to get some sort of feedback, If your telling me that i have to go searching through your forums to get help on sound, THEN TELL ME?! You have a system right here you can use to communicate and you're literally just pressing a button to close out an actual problem. The only other forum ive read about this issue was the one ive literally just called you out on for not doing anything about the issue, so nothings been resolved and you didnt even spend a second reading this issue.

**Comment by Phatboysquad** [comment]
@NordicGamerFE  
![image](https://github.com/user-attachments/assets/95fb8978-ed6c-498c-9780-3bd65ca7554f)
 How is this completed????

**Comment by ekirk81** [comment]
Expected result? Actual result? I didn't understand what you were trying to ask.  I'm sorry I sought help or submitted a bug report.  You come across as hostile and fragile. You left my post lock because of someone else's comment on it. The solution was deleting the Sound device option mod. Which works fine in other modpacks but isn't implemented correctly here.

**Comment by NordicGamerFE** [comment]
> Expected result? Actual result? I didn't understand what you were trying to ask. I'm sorry I sought help or submitted a bug report. You come across as hostile and fragile. You left my post lock because of someone else's comment on it. The solution was deleting the Sound device option mod. Which works fine in other modpacks but isn't implemented correctly here.

I dont care much about expected and actual. the most important part is version, launcher and additional mods that were left out. i simply said "Form is not filled in with all details." and added the needs more information tag. i waited for additons but they never came and i also started testing and found the issue eventally from discord from a user who gave me all the information i needed i later updated the pack to implement a fix. i left your post locked because its an already fixed issue and i dont offer support to outdated versions of the pack. i never ment to be hostile towards you if it came across that way i am sorry.
