### ISSUE TITLE
Fire Resistance still show flames

### ISSUE THREAD

**Issue by NordicGamerFE** [NordicGamerFE/Ocean-Outlast#28]
Description:
Fire effect even with fire resistance

Expected Result:
No fire effect when fire resistance is in place

Need to find fix

**Comment by cenodis** [comment]
Removing the overlay entirely would be a bad idea because you cant tell if you are on fire or not. The game still considers you on fire and if your fire resistance stops you will take damage again.
It would be a better idea to change the overlays texture so it takes up considerably less screen space while still being visible. This can most easily be done via a custom texture like some texturepacks have done.
