### ISSUE TITLE
Quest Wrong Item Required

### ISSUE THREAD

**Issue by WaterMelwin** [NordicGamerFE/Ocean-Outlast#70]
Version: Expert Version 54

Description: The steel production quest asks for steel dust, when you can not get steel dust only steel blend.

Expected Result: Quest should ask for steel blend.

Actual Result: Quest requests steel dust.

Did you add additional mods?
no

**Comment by blahthebiste** [comment]
Seconded. It's blocking me from finishing the steel production quest

**Comment by WaterMelwin** [comment]
> Seconded. It's blocking me from finishing the steel production quest

just spawn the item in. Owner doesnt seem to be working on the pack anymore

**Comment by blahthebiste** [comment]
Darn, I was enjoying this pack. Thanks for letting me know

**Comment by FagSoft** [comment]
@BabBimmaBome & @blahthebiste : I can confirm that he's still working on it, so that bit is not quite true. However, things do take time, so no ETA on the next update yet.

They are working on getting the latest patch out on AT Launcher though. In the meantime you can install it "manually" via the add Curseforge pack button.
